name: Update SS Configs

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Debug directory contents
      run: |
        pwd
        ls -la
    
    - name: Run config fetcher
      run: |
        python fetch_configs.py
      continue-on-error: false
    
    - name: Check if ProjectAinita_Singbox.json exists
      run: |
        if [ ! -f ProjectAinita_Singbox.json ]; then
          echo "ProjectAinita_Singbox.json was not created!"
          exit 1
        fi
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ProjectAinita_Singbox.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update ProjectAinita_Singbox.json [skip ci]"
          git push
        fi
